# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('imgUrl', models.TextField()),
                ('source', models.TextField()),
                ('author', models.TextField()),
                ('introduce', models.TextField()),
                ('type', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
